### ISSUE TITLE
There are a few minor problems for NAS-LID, i can not run this AutoML framework

### ISSUE THREAD

**Issue by fly2tortoise** [marsggbo/NAS-LID#1]
(Hyperbox) tom@tom:~/150/NAS/NAS-LID/hyperbox/hyperbox_app/distributed$ bash ./scripts/fewshot/fewshot_search_nb201.sh 0 nb201_c10_ID_mincut_sp_16splits "logger.wandb.offline=True trainer.strategy=null engine.split_criterion=ID engine.split_method=mincut"
fewshot_search_nb201_c10_ID_mincut_sp_16splits
Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/hyperbox/run.py", line 15, in <module>
    root = pyrootutils.setup_root(__file__, dotenv=True, pythonpath=True) # config.paths.root_dir
  File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/pyrootutils/pyrootutils.py", line 151, in setup_root
    path = find_root(search_from, indicator)
  File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/pyrootutils/pyrootutils.py", line 73, in find_root
    raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")

FileNotFoundError: Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')

**Comment by JessonWong** [comment]
I met the same problem when I ran the following instruction: bash ./scripts/fewshot/fewshot_search_nb201.sh 0 nb201_c10_ID_mincut_sp_16splits "logger.wandb.offline=True trainer.strategy=null engine.split_criterion=ID engine.split_method=mincut"

**Comment by L1690941806** [comment]
> (Hyperbox) tom@tom:~/150/NAS/NAS-LID/hyperbox/hyperbox_app/distributed$ bash ./scripts/fewshot/fewshot_search_nb201.sh 0 nb201_c10_ID_mincut_sp_16splits "logger.wandb.offline=True trainer.strategy=null engine.split_criterion=ID engine.split_method=mincut" fewshot_search_nb201_c10_ID_mincut_sp_16splits Traceback (most recent call last): File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/hyperbox/run.py", line 15, in root = pyrootutils.setup_root(**file**, dotenv=True, pythonpath=True) # config.paths.root_dir File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/pyrootutils/pyrootutils.py", line 151, in setup_root path = find_root(search_from, indicator) File "/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/pyrootutils/pyrootutils.py", line 73, in find_root raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
> 
> FileNotFoundError: Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')
hello! I met the same problem when I ran the code. Have you already sovled this problem？

**Comment by L1690941806** [comment]
> I met the same problem when I ran the following instruction: bash ./scripts/fewshot/fewshot_search_nb201.sh 0 nb201_c10_ID_mincut_sp_16splits "logger.wandb.offline=True trainer.strategy=null engine.split_criterion=ID engine.split_method=mincut"

hello! I met the same problem, have you already solved this problem?

**Comment by marsggbo** [comment]
The error may be caused by `pyrootutils` lib. You can try to delete related code (e.g., `root = pyrootutils.setup_root(__file__, dotenv=True, pythonpath=True))`  in `/home/tom/anaconda3/envs/Hyperbox/lib/python3.9/site-packages/hyperbox/run.py`
