### ISSUE TITLE
FileNotFoundError: Project root directory not found

### ISSUE THREAD

**Issue by L1690941806** [marsggbo/NAS-LID#2]
hello，when I run the
bash ./scripts/fewshot/fewshot_search_nb201.sh 0 nb201_c10_ID_mincut_sp_16splits \
"logger.wandb.offline=True trainer.strategy=null engine.split_criterion=ID engine.split_method=mincut"
I met the following problems:
Traceback (most recent call last):
  File "D:\apps\Anaconda\envs\naslid\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
    exec(code, run_globals)
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hyperbox\run.py", line 15, in <module>
    root = pyrootutils.setup_root(__file__, dotenv=True, pythonpath=True) # config.paths.root_dir
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\pyrootutils\pyrootutils.py", line 151, in setup_root
    path = find_root(search_from, indicator)
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\pyrootutils\pyrootutils.py", line 73, in find_root
    raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
FileNotFoundError: Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')
how do I solve these problems?

**Comment by marsggbo** [comment]
please refer to #1
