### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by L1690941806** [marsggbo/NAS-LID#3]
when I ran in windows，I met the following problem，how can I solve this problem？looking forward to your reply
$ bash ./scripts/fewshot/fewshot_search_nb201.sh 0 nb201_c10_ID_mincut_sp_16splits "logger.wandb.offline=True trainer.strategy=null engine.split_criterion=ID engine.spl
it_method=mincut"
fewshot_search_nb201_c10_ID_mincut_sp_16splits
D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\config_loader_impl.py:214: UserWarning: provider=hydra.searchpath in command-line, path=hyperbox_app.dist
ributed.configs is not available.
  warnings.warn(
D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra
.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[2024-05-17 15:41:47] [INFO] [D:\apps\Anaconda\envs\naslid\lib\site-packages\hyperbox\utils\utils.py:99 (hyperbox.utils.utils)] Disabling python warnings! <config.ignor
e_warnings=True>
Error executing job with overrides: ['experiment=fewshot_search_nb201.yaml', 'logger.wandb.name=fewshot_search_nb201_c10_ID_mincut_sp_16splits', '+trainer.gpus=0', '+mo
del.is_net_parallel=False', 'logger.wandb.offline=True', 'trainer.strategy=null', 'engine.split_criterion=ID', 'engine.split_method=mincut']
Traceback (most recent call last):
  File "D:\apps\Anaconda\envs\naslid\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\apps\Anaconda\envs\naslid\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hyperbox\run.py", line 50, in <module>
    main()
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\main.py", line 90, in decorated_main
    _run_hydra(
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\utils.py", line 389, in _run_hydra
    _run_app(
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\utils.py", line 452, in _run_app
    run_and_report(
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\utils.py", line 216, in run_and_report
    raise ex
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\utils.py", line 213, in run_and_report
    return func()
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\hydra\core\utils.py", line 186, in run_job
  File "D:\apps\Anaconda\envs\naslid\lib\site-packages\rich\console.py", line 2046, in _check_buffer
    write("".join(batch))
UnicodeEncodeError: 'gbk' codec can't encode character '\u2699' in position 0: illegal multibyte sequence
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

**Comment by marsggbo** [comment]
You can refer to this issue: https://github.com/marsggbo/hyperbox/issues/33#issuecomment-1261062037
